In [1]:
# numpy and pandas for data manipulation
import numpy as np
import pandas as pd
import sys
import networkx as nx
import os
import warnings
# matplotlib and seaborn for plotting

import matplotlib.pyplot as plt
import seaborn as sns

# sklearn preprocessing for dealing with categorical variables
from sklearn.preprocessing import LabelEncoder

import os

# Suppress warnings
import warnings
warnings.filterwarnings('ignore')

# matplotlib and seaborn for plotting
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
ROOT_PACKAGE_DIRECTORY = '/Users/bede01/Documents/work/phd-papers/ml-workload-optimization/code/jupyter'
ROOT_DATA_DIRECTORY = '/Users/bede01/Documents/work/phd-papers/ml-workload-optimization/code/jupyter/data'
sys.path.append(ROOT_PACKAGE_DIRECTORY)

# Experiment Graph
from experiment_graph.execution_environment import ExecutionEnvironment as ee


# Suppress warnings
warnings.filterwarnings('ignore')
% matplotlib inline


try:
    import pygraphviz
    from networkx.drawing.nx_agraph import graphviz_layout
except ImportError:
    try:
        import pydot
        from networkx.drawing.nx_pydot import graphviz_layout
    except ImportError:
        raise ImportError("This example needs Graphviz and either "
                          "PyGraphviz or pydot")

In [4]:
app_train = ee.load(ROOT_DATA_DIRECTORY + '/home-credit-default-risk/preprocessed_train.csv')

Node Exists!!!


In [11]:
app_test = ee.load(ROOT_DATA_DIRECTORY + '/home-credit-default-risk/preprocessed_test.csv')

Node Exists!!!


In [12]:
# Using Experiment Database
from sklearn.preprocessing import MinMaxScaler, Imputer

# Drop the target from the training data
if 'TARGET' in app_train.get().columns:
    train = app_train.drop(columns = ['TARGET'])
else:
    train = app_train.copy()
    
# Feature names
features = list(train.get().columns)

# Copy of the testing data
test = app_test.copy()

# Median imputation of missing values
sk_imputer = Imputer(strategy = 'median')

# Scale each feature to 0-1
sk_scaler = MinMaxScaler(feature_range = (0, 1))

# Fit on the training data
imputer = train.fit_sk_model(sk_imputer)


# Transform both training and testing data
train = imputer.transform(train)
test = imputer.transform(test)

# Repeat with the scaler
scaler = train.fit_sk_model(sk_scaler)
train = scaler.transform(train)
test = scaler.transform(test)

print('Training data shape: ', train.shape().get())
print('Testing data shape: ', test.shape().get())

('Training data shape: ', (307511, 240))


('Testing data shape: ', (48744, 240))


In [13]:
for n in ee.graph.graph.nodes:
    print ee.graph.graph.nodes[n]['data']
    print ee.graph.graph.nodes[n]['size']

563.069526672
88
88.9275970459
6.103515625e-05
563
0.0
89.2529983521
0.0
563.069526672
6.103515625e-05
6.86645507812e-05
561.016669273
6.86645507812e-05
89.2529983521
0.0
0.0


In [12]:
%%timeit
from sklearn.preprocessing import MinMaxScaler, Imputer

# Drop the target from the training data
if 'TARGET' in app_train_pd:
    train = app_train_pd.drop(columns = ['TARGET'])
else:
    train = app_train_pd.copy()
    
# Feature names
features = list(train.columns)

# Copy of the testing data
test = app_test_pd.copy()

# Median imputation of missing values
imputer = Imputer(strategy = 'median')

# Scale each feature to 0-1
scaler = MinMaxScaler(feature_range = (0, 1))

# Fit on the training data
imputer.fit(train)

# Transform both training and testing data
train = imputer.transform(train)
test = imputer.transform(test)

# Repeat with the scaler
scaler.fit(train)
train = scaler.transform(train)
test = scaler.transform(test)

print('Training data shape: ', train.shape)
print('Testing data shape: ', test.shape)

KeyboardInterrupt: 

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import MinMaxScaler, Imputer

# Make the model with the specified regularization parameter
sk_imputer = Imputer(strategy = 'median')
sk_log_reg = LogisticRegression(C = 0.0001)
train = app_train[['CNT_CHILDREN','AMT_INCOME_TOTAL','AMT_ANNUITY','FLAG_DOCUMENT_18']]
test = app_test[['CNT_CHILDREN','AMT_INCOME_TOTAL','AMT_ANNUITY','FLAG_DOCUMENT_18']]
# Fit on the training data
imputer = train.fit_sk_model(sk_imputer)

# Transform both training and testing data
train = imputer.transform(train)
test = imputer.transform(test)

train_labels = app_train['TARGET']
# Train on the training data
log_reg = train.fit_sk_model_with_labels(sk_log_reg, train_labels)

In [ ]:
pred = log_reg.predict_proba(test)

In [ ]:
pred.get()[:]

In [5]:
temp = app_train['SK_ID_CURR'].concat(app_train['TARGET'])

In [12]:
temp = app_train.head(100)

In [15]:
from sklearn.model_selection import KFold
k_fold = KFold(n_splits = 5, shuffle = True, random_state = 50)

for t, v in k_fold.split(temp.get()):
    print t
    print v

[ 0  1  2  4  5  6  7  9 10 11 12 13 14 19 20 21 22 23 24 26 27 28 29 30 31
 32 33 35 36 37 41 42 43 44 45 46 48 49 51 54 55 56 58 59 60 61 62 63 64 65
 66 67 68 70 71 72 73 74 75 76 77 78 81 82 83 84 85 86 88 89 90 91 92 93 94
 95 96 97 98 99]
[ 3  8 15 16 17 18 25 34 38 39 40 47 50 52 53 57 69 79 80 87]
[ 0  1  2  3  4  5  6  7  8  9 10 11 13 15 16 17 18 19 20 22 24 25 26 27 28
 29 30 31 33 34 35 36 38 39 40 41 43 45 46 47 48 49 50 51 52 53 55 56 57 60
 61 63 64 65 66 67 68 69 70 71 73 74 75 77 78 79 80 81 83 84 85 87 88 89 92
 93 94 96 97 99]
[12 14 21 23 32 37 42 44 54 58 59 62 72 76 82 86 90 91 95 98]
[ 0  2  3  4  5  6  8 10 11 12 14 15 16 17 18 19 20 21 22 23 25 26 29 30 31
 32 33 34 35 37 38 39 40 41 42 43 44 47 48 49 50 51 52 53 54 57 58 59 60 62
 63 64 66 67 68 69 70 71 72 73 74 76 77 78 79 80 82 83 84 85 86 87 89 90 91
 93 94 95 96 98]
[ 1  7  9 13 24 27 28 36 45 46 55 56 61 65 75 81 88 92 97 99]
[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 20 21 22 23 24 25 26 27
 28

In [9]:
from sklearn.model_selection import KFold
from sklearn.metrics import roc_auc_score
import lightgbm as lgb
import gc

def model(features, test_features, encoding = 'ohe', n_folds = 5):
    
    """Train and test a light gradient boosting model using
    cross validation. 
    
    Parameters
    --------
        features (DataFrame): 
            dataframe of training features to use 
            for training a model. Must include the TARGET column.
        test_features (DataFrame): 
            dataframe of testing features to use
            for making predictions with the model. 
        encoding (str, default = 'ohe'): 
            method for encoding categorical variables. Either 'ohe' for one-hot encoding or 'le' for integer label encoding
            n_folds (int, default = 5): number of folds to use for cross validation
        
    Return
    --------
        submission (DataFrame): 
            dataframe with `SK_ID_CURR` and `TARGET` probabilities
            predicted by the model.
        feature_importances (DataFrame): 
            dataframe with the feature importances from the model.
        valid_metrics (DataFrame): 
            dataframe with training and validation metrics (ROC AUC) for each fold and overall.
        
    """
    
    # Extract the ids
    train_ids = features['SK_ID_CURR']
    test_ids = test_features['SK_ID_CURR']
    
    # Extract the labels for training
    labels = features['TARGET']
    
    # Remove the ids and target
    features = features.drop(columns = ['SK_ID_CURR', 'TARGET'])
    test_features = test_features.drop(columns = ['SK_ID_CURR'])
    
    
    # One Hot Encoding
    if encoding == 'ohe':
        features = features.onehot_encode()
        test_features = test_features.onehot_encode()
        
        # Align the dataframes by the columns
        for c in features.get().columns:
            if c not in test_features.get().columns:
                features = features.drop(c)
                
        # No categorical indices to record
        cat_indices = 'auto'
    
    # Integer label encoding
    elif encoding == 'le':
        
        # Create a label encoder object
        le = LabelEncoder()
        # List for storing categorical indices
        cat_indices = []

        for i, col in enumerate(features.select_dtypes('object').get().columns):
            # we are not using nunique because it discard nan
            label_encoder = features[col].fit_sk_model(le)

            transformed_feature = features.transform_col(features[col], col)
            features = features.drop(col)
            features = features.add_columns(transformed_feature, col)

            transformed_feature_test = model.transform_col(test_features[col], col)
            test_features = test_features.drop(col)
            test_features = test_features.add_columns(transformed_feature_test, col)
            cat_indices.append(i)    
    
    # Catch error if label encoding scheme is not valid
    else:
        raise ValueError("Encoding must be either 'ohe' or 'le'")
        
    print('Training Data Shape: ', features.shape().get())
    print('Testing Data Shape: ', test_features.shape().get())
    
    # Extract feature names
    feature_names = list(features.get().columns)


    # Create the model
    lgb_model = lgb.LGBMClassifier(n_estimators=10, objective = 'binary', 
                               class_weight = 'balanced', learning_rate = 0.05, 
                               reg_alpha = 0.1, reg_lambda = 0.1, 
                               subsample = 0.8, n_jobs = -1, random_state = 50)
        
    model = features.fit_sk_model_with_labels(lgb_model, labels, custom_args={'eval_metric':'auc',
                                                                             'categorical_feature':cat_indices,
                                                                             'verbose':200})    
        
    # Record the best iteration
    best_iteration = model.get().best_iteration_
    
        
    # Make predictions
    test_predictions = model.predict_proba(test_features, custom_args={'num_iteration':best_iteration})[1] 
        
    
    test_predictions.setname('TARGET')
    # Make the submission dataframe
    submission = test_ids.concat(test_predictions)
    
    feature_importances = model.feature_importances(feature_names)
   

    return submission, feature_importances

In [10]:
s,f = model(app_train, app_test)

('Training Data Shape: ', (307511, 241))
('Testing Data Shape: ', (48744, 241))


In [13]:
f.get()

feature  importance
0                                CNT_CHILDREN           0
1                            AMT_INCOME_TOTAL           0
2                                  AMT_CREDIT           2
3                                 AMT_ANNUITY           1
4                             AMT_GOODS_PRICE           3
5                  REGION_POPULATION_RELATIVE           0
6                                  DAYS_BIRTH          37
7                               DAYS_EMPLOYED           8
8                           DAYS_REGISTRATION           0
9                             DAYS_ID_PUBLISH           0
10                                OWN_CAR_AGE           3
11                                 FLAG_MOBIL           0
12                             FLAG_EMP_PHONE           0
13                            FLAG_WORK_PHONE           0
14                           FLAG_CONT_MOBILE           0
15                                 FLAG_PHONE           0
16                                 FLAG_EMAIL           0
17                            CNT_FAM_MEMBERS           0
18                       REGION_RATING_CLIENT           0
19                REGION_RATING_CLIENT_W_CITY           0
20                    HOUR_APPR_PROCESS_START           0
21                 REG_REGION_NOT_LIVE_REGION           0
22                 REG_REGION_NOT_WORK_REGION           0
23                LIVE_REGION_NOT_WORK_REGION           0
24                     REG_CITY_NOT_LIVE_CITY           0
25                     REG_CITY_NOT_WORK_CITY           0
26                    LIVE_CITY_NOT_WORK_CITY           0
27                               EXT_SOURCE_1          80
28                               EXT_SOURCE_2          66
29                               EXT_SOURCE_3          50
..                                        ...         ...
211                 ORGANIZATION_TYPE_Telecom           0
212           ORGANIZATION_TYPE_Trade: type 1           0
213           ORGANIZATION_TYPE_Trade: type 2           0
214           ORGANIZATION_TYPE_Trade: type 3           0
215           ORGANIZATION_TYPE_Trade: type 4           0
216           ORGANIZATION_TYPE_Trade: type 5           0
217           ORGANIZATION_TYPE_Trade: type 6           0
218           ORGANIZATION_TYPE_Trade: type 7           0
219       ORGANIZATION_TYPE_Transport: type 1           0
220       ORGANIZATION_TYPE_Transport: type 2           0
221       ORGANIZATION_TYPE_Transport: type 3           0
222       ORGANIZATION_TYPE_Transport: type 4           0
223              ORGANIZATION_TYPE_University           0
224                     ORGANIZATION_TYPE_XNA           0
225          FONDKAPREMONT_MODE_not specified           0
226       FONDKAPREMONT_MODE_org spec account           0
227       FONDKAPREMONT_MODE_reg oper account           0
228  FONDKAPREMONT_MODE_reg oper spec account           0
229             HOUSETYPE_MODE_block of flats           0
230           HOUSETYPE_MODE_specific housing           0
231             HOUSETYPE_MODE_terraced house           0
232                  WALLSMATERIAL_MODE_Block           0
233                  WALLSMATERIAL_MODE_Mixed           0
234             WALLSMATERIAL_MODE_Monolithic           0
235                 WALLSMATERIAL_MODE_Others           0
236                  WALLSMATERIAL_MODE_Panel           0
237           WALLSMATERIAL_MODE_Stone, brick           0
238                 WALLSMATERIAL_MODE_Wooden           0
239                    EMERGENCYSTATE_MODE_No           0
240                   EMERGENCYSTATE_MODE_Yes           0

[241 rows x 2 columns]

In [ ]:
model = model.fit(app_train.get(),features['TARGET'].get(), )    